### PR TITLE
Add channel caching to limit API requests

### PR DESCRIPTION
**Pull request by mrkaye97**
This PR adds channel caching (in a bad, naive way. open to suggestions for how to do it better. maybe a tempfile?) in order to limit API requests. The idea is that we cache the users / channels in the workspace at setup time so that we don't need to request them every time we go to send a Slack message.

This PR also cleans up some documentation.

### CODE REVIEW

**Comment by yonicd** [comment]
This is partly the reason why slackteams was created. 

slackr dcf should integrate fine with it.

**Comment by mrkaye97** [comment]
> This is partly the reason why slackteams was created.
> 
> slackr dcf should integrate fine with it.

@yonicd Would the idea be to just plug into `slackteams` to get this info? That would definitely be a bigger PR, so this seems like a better first pass approach to me.

**Comment by yonicd** [comment]
I dont think that is a PR it would be just adding a package dependency. all that slackteams expects would be the api token to work.

**Comment by mrkaye97** [comment]
> I dont think that is a PR it would be just adding a package dependency. all that slackteams expects would be the api token to work.

@yonicd A couple questions:

1. _Which_ API token is the one that `slackteams` wants? I think that the Slack API gives you three different ones at setup time. The one I'm relying on is the Bot User OAuth Token.
2. What's the rationale for hooking into `slackteams` instead of just doing this? From my point of view, it seems like it adds another dependency here for a small feature which doesn't totally seem worth the risk to me.

I think I may make this cache into a tempfile so then it can just read from there instead of saving to the global environment, but this seems like a preferable solution to me as opposed to adding the dependency

**Comment by yonicd** [comment]
ok.

**Comment by mrkaye97** [comment]
@hrbrmstr FYI, I just published this new version to CRAN. It says they're waiting on your approval

**Pull request merged**
