### PR TITLE
fix duration in slackr_history if posted_from_time is not provided

### LINKED ISSUE #181: duration argument in slackr_history() is not respected if posted_from_time is not specified
In `slackr_history()` the `duration` argument has no effect in contrast with the documentation if `posted_from_time` is not specified (which is the default).

I think the problem is in this line: 
https://github.com/mrkaye97/slackr/blob/master/R/slackr_history.R#L34 Instead of `missing(posted_from_time)` it should check if the `posted_to_time` is provided as the code and logic relies on that. The functions works as expected if I specify `duration = "whatever dummy value"`

Also I think the documentation could be improved as the default is not 24 hours, but no limit on the duration.
https://github.com/mrkaye97/slackr/blob/master/R/slackr_history.R#L13

I am happy to prepare a PR if you are open to it.

### PR DESCRIPTION
**Pull request by czeildi**
Fixes #181

### CODE REVIEW

**Comment by czeildi** [comment]
I am not sure if I should also include a version bump and news item with this tiny change

**Comment by mrkaye97** [comment]
> I am not sure if I should also include a version bump and news item with this tiny change

Yes, please put in a patch version bump and add a note to the changelog! Thanks!

**Comment by czeildi** [comment]
I removed methods from Description file which caused a Note in R cmd check and bumped the roxygen version number so that r cmd check does not complain about mismatch, but the test failures are not related to this PR, I believe. Many of them complain about slack not authed, maybe the slack token set up in github actions is expired?

**Comment by mrkaye97** [comment]
> I removed methods from Description file which caused a Note in R cmd check and bumped the roxygen version number so that r cmd check does not complain about mismatch, but the test failures are not related to this PR, I believe. Many of them complain about slack not authed, maybe the slack token set up in github actions is expired?

Ah, it's actually because I don't think GH likes sharing its secrets to a fork. Let me look into this for a bit and see if I can set up a better way of managing secrets so that I can share the token your CI runs need. I'll get back to you on this in a bit

**Comment by mrkaye97** [comment]
alright @czeildi, do you mind trying to rebase your branch on top of the latest upstream `master`? I just changed some things about how the CI works and fixed a couple failing tests, so I _think_ (75% chance) that if you rebase and I approve your CI run, all the tests should pass 🤞. and thanks for putting up with the toil here! hopefully the CI process is a little smoother going forward...

**Comment by czeildi** [comment]
> alright @czeildi, do you mind trying to rebase your branch on top of the latest upstream `master`? I just changed some things about how the CI works and fixed a couple failing tests, so I _think_ (75% chance) that if you rebase and I approve your CI run, all the tests should pass crossed_fingers. and thanks for putting up with the toil here! hopefully the CI process is a little smoother going forward...

Thank you for the help! The sync button for forks created a merge commit instead or rebasing, is that a problem?

**Comment by mrkaye97** [comment]
Merge commit should be fine! Looks like my fix didn't work though :/

The issue is that the secrets I have set up aren't getting injected into your CI environment correctly. In an effort to not stall this PR for forever, I'm going to try merging from your fork into my own branch of the same name, and running CI there. I think it'll all pass once that happens 🤦

**Pull request merged**
