### PR TITLE
add tex_slackr

### PR DESCRIPTION
**Pull request by yonicd**
write to slack compiled tex to png using [texPreview](https://github.com/metrumresearchgroup/texPreview/), same script as gg_slackr but changed the function posting to file.upload (image device/tex/pdf)

### CODE REVIEW

**Comment by hrbrmstr** [comment]
Looks 👍 (and #ty for editing the DESCRIPTION as well)

**Comment by yonicd** [comment]
happy i can ctb. btw i ran up against the request limits of channel.history when trying to run progress bars per node/core (in the end i had to call once on init and once a finish [example](https://twitter.com/yoniceedee/status/896216391149342720)). if you have any ideas of getting around that, it would be cool.

**Comment by hrbrmstr** [comment]
I need to go back and re-visit their entire API. It's changed quite a bit since `slackr` was born and it's likely I can optimize some bits.

**Comment by yonicd** [comment]
Their use of epochs instead of hashes to index channel messages is slightly annoying

**Pull request merged**
